dist: trusty
sudo: required
language: go

install:
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${GOPATH}
  - curl https://glide.sh/get | sh
  - go get -u github.com/EUDAT-GEF/GEF || true
  - cd $GOPATH/src/github.com/EUDAT-GEF/GEF

script:
  - make build