dist: trusty
sudo: required
language: go

before_install:
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${GOPATH}

script:
  - go test github.com/EUDAT-GEF/BridgIt/api, github.com/EUDAT-GEF/BridgIt/utils, github.com/EUDAT-GEF/BridgIt/def