dist: trusty
sudo: required
language: go

before_install:
  - echo ${TRAVIS_BUILD_DIR}
  - echo ${GOPATH}
  - go get -u github.com/EUDAT-GEF/GEF
  - cd $GOPATH/src/github.com/EUDAT-GEF/GEF
  - make build

script: echo "Hello"